server:
   port: 9090

spring:
   application:
      name: zuul
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:9091//eureka/
zuul:  
   routes:
     AIRLINESERVICE:    
         path: /airlines/**
         url:  AIRLINESERVICE
     LOGINSERVICE:
         path: /authenticate/**
         url:  LOGINSERVICE
     BOOKINGSERVICE:
         path: /booking/**
         url:  BOOKINGSERVICE


jwt:
   secret:javainuse